# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/hx07v5b7x5rl6db17npmf2lb1pw91y8j-hm-session-vars.fish



status is-login; and begin

    # Login shell initialisation


end

status is-interactive; and begin

    # Abbreviations


    # Aliases
    alias la 'eza -a'
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'

    # Interactive shell initialisation
    /nix/store/3r53s603m24fb6wm2cmkvgw8x9fgmdpv-fzf-0.56.0/bin/fzf --fish | source

    /nix/store/99ylqh5nfayakzpyg13zpk38w7dyi0kp-zoxide-0.9.6/bin/zoxide init fish | source

    function yy
        set tmp (mktemp -t "yazi-cwd.XXXXX")
        yazi $argv --cwd-file="$tmp"
        if set cwd (cat -- "$tmp"); and [ -n "$cwd" ]; and [ "$cwd" != "$PWD" ]
            builtin cd -- "$cwd"
        end
        rm -f -- "$tmp"
    end

    if test "$TERM" != dumb
        eval (/etc/profiles/per-user/raikusy/bin/starship init fish)

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/raikusy/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/7diqlbq62s6xr8444vjii72ry59j3g4d-direnv-2.35.0/bin/direnv hook fish | source


end
